#!/bin/bash


SERVICE='Api'
PID=$(ps ax | grep -v grep | grep $SERVICE | awk '{print $1}')

case "$1" in
    start)
        echo -e "Starting the Interpreter API: "
	python /root/interpreter/interpreter/Apilistener.py & 
        ;;
    stop)
        if ps ax | grep -v grep | grep $SERVICE > /dev/null
	then
    	echo -e "Stopping the Interpreter API ..."
    	kill $PID
	else
    	echo -e "The Interpreter API is not running, no need to stop it"
	fi
        ;;
    status)
	if ps ax | grep -v grep | grep $SERVICE > /dev/null
	then
		echo -e "The Interpreter API is running"
	else
		echo -e "Rhe Interpreter API is not running"
	fi
	;;
    reload|restart)
        $0 stop
        $0 start
        ;;
    *)
        echo -e "Usage: $0 start|stop|restart|reload"
        exit 1
esac
exit 0
